<div class="white-bg">    
    <div class="container career-inner">
        <div class="row">
            <div class="col-md-12 career-head">
                <h1 class="wow fadeIn">
                	<br/>
                	Instalaciones electricas
                	</br>
                </h1>
            </div>
        </div>
 	</div>
</div>
<div class="white-bg">      
	<div class="container career-inner">		
        <hr>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 career-contact">
                <p class="text-center wow pulse">         
                	<i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>Instalaciones eléctricas residenciales</b>                	
                </p>
                <p class="text-center wow pulse">   
	                <i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>Subestaciones</b>
                </p>
            </div>
        </div>
        <hr>
    </div>
</div>
<div class="white-bg">    
    <div class="container career-inner">
        <div class="row">
            <div class="col-md-12 career-head">
                <h1 class="wow fadeIn">
                	<br/>
                	Instalaciones especiales
                	</br>
                </h1>
            </div>
        </div>
 	</div>
</div>
<div class="white-bg">      
	<div class="container career-inner">		
        <hr>
        <div class="row">
            <div class="col-md-4 col-md-offset-4 career-contact">
                <p class="text-center wow pulse">         
                	<i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>Control de acceso </b>                	
                </p>
                <p class="text-center wow pulse">   
	                <i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>Sistemas ITS</b>
                </p>
                <p class="text-center wow pulse">   
	                <i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>Detecci&oacute;n y Extinci&oacute;n de Incendios</b>
                </p>
                <p class="text-center wow pulse">   
	                <i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>Cable estructurado</b>
                </p>
                <p class="text-center wow pulse">   
	                <i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>Fibra &oacute;ptica</b>
                </p>
                <p class="text-center wow pulse">   
	                <i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>CCTV</b>
                </p>
                <p class="text-center wow pulse">   
	                <i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>Voz y datos</b>
                </p>
                <p class="text-center wow pulse">   
	                <i class="fa fa-asterisk" aria-hidden="true"></i>
                	<b>Hidr&aacute;ulica</b>
                </p>
            </div>
        </div>
        <hr>
    </div>
</div>		