<!-- Sequence Modern Slider -->
<div id="da-slider" class="da-slider">
	<div class="da-slide">
   		<div class="container">
        	<div class="row">
           		<div class="col-md-12">
              		<h2>
                		<i>Ingenier&iacute;a</i><br>
                		<i>Electromecanica</i><br>
                		<i>Innovaci&oacute;n</i>
              		</h2>
              		<p>
                		<i>Bienvenidos a</i><br />
                		<i>IEII</i>
              		</p>
              		<a href="/acercade" class="btn btn-info btn-lg da-link">M&aacute;s</a>
              		<div class="da-img">
                		<img src="/img/parallax-slider/images/ieii2.png" alt="image01" />
              		</div>
            	</div>
          	</div>
        </div>
	</div>
	<div class="da-slide">
		<div class="container">
        	<div class="row">
          		<div class="col-md-12">
        			<h2>
          				<i>Ingeniar&iacute;a</i><br />
          				<i>Mantenimiento</i><br />
          				<i>Instalaciones</i>
        			</h2>
        			<p>
          				<i>Y muchos servicios</i><br />
          				<i>mas</i>
        			</p>
        			<a href="#" class="btn btn-info btn-lg da-link">
          				Servicios
        			</a>
        			<div class="da-img">
          				<img src="/img/parallax-slider/images/ieii2.png" alt="image01" />
        			</div>
      			</div>
          	</div>
        </div>
	</div>	
    <nav class="da-arrows">
    	<span class="da-arrows-prev"></span>
        <span class="da-arrows-next"></span>
    </nav>
</div>
<div class="container">
	<div class="row mar-b-50">
    	<div class="col-md-12">
        	<div class="text-center feature-head wow fadeInDown">
            	<h1 class="">Bienvenido a IEII</h1>
          	</div>
          	<div class="feature-box">
            	<div class="col-md-4 col-sm-4 text-center wow fadeInUp">
              		<div class="feature-box-heading">
                		<em>
			                <img src="/img/1.png" alt="" width="100" height="100">
                		</em>
                		<h4>
                  			<b>Ingenier&iacute;a</b>
                		</h4>
              		</div>
              		<p style="text-align: justify;">
                		INSTALACIONES ELECTROMECANICAS, INGENIERIA E INNOVACI&Oacute;N IMPLEMENTA EN SU 
                		INGENIER&Iacute;A, DIVERSAS TECNOLOG&iacute;AS INNOVADORAS QUE PERMITEN MAXIMIZAR 
                		EFICIENCIAS INTEGRANDO TODO EL ESTUDIO T&Eacute;CNICO QUE REQUIERE EL PROYECTO.
						<br/>
						LAS SOLUCIONES SE DAR&Acute;N DE MANERA FLU&Iacute;DA Y CONSISTENTE, ENFATIZANDO 
						NUESTRO RETO DE DISE&Ntilde;AR, PLANIFICAR Y DESARROLLAR PROYECTOS DE INSTALACIONES 
						ELECTRICAS, ELECTROMECANICAS, ESPECIALES Y TELECOMUNICACIONES M&Aacute;S ADECUADO A 
						TUS NECESIDADES.
              		</p>
            	</div>
            	<div class="col-md-4 col-sm-4 text-center wow fadeInUp">
              		<div class="feature-box-heading">
                		<em>
                  			<img src="/img/2.png" alt="" width="100" height="100">
                		</em>
                		<h4>
                  			<b>Mantenimiento</b>
                		</h4>
              		</div>
              		<p style="text-align: justify;">
                		INSTALACIONES ELECTROMECANICAS, INGENIER&Iacute;A E INNOVACION TIENE COMO OBJETIVO 
                		PRINCIPAL OFRECER CON CALIDAD Y PROFESIONALISMO SERVICIOS DE MANTENIMIENTO, 
                		PREVENTIVO, CORRECTIVO Y PREDICTIVO PARA EQUIPOS E INSTALACIONES DE MEDIA Y BAJA 
                		TENSI&Oacute;N ASI COMO INSTALACIONES ESPECIALES, GARANTIZANDO AHORRO DE ENERG&Iacute;A 
                		EL&Eacute;CTRICA E INCREMENTAR LA VIDA &Uacute;TIL DE SUS ACTIVOS.
              		</p>
            	</div>
            	<div class="col-md-4 col-sm-4 text-center wow fadeInUp">
              		<div class="feature-box-heading">
                		<em>
                  			<img src="/img/3.png" alt="" width="100" height="100">
                		</em>
                		<h4>
                  			<b>Instalaciones</b>
                		</h4>
              		</div>
              		<p style="text-align:justify;">
                		INSTALACIONES ELECTROMECANICAS, INGENIER&Iacute;A E INNOVACI&Oacute;N BUSCA 
                		DESARROLLAR Y EJECUTAR INSTALACIONES ELECTRICAS, ELECTROMECANICAS Y ESPECIALES, 
                		PARA LA INDUSTRIA, EDIFICACI&Oacute;N VERTICAL, EDIFICACI&Oacute;N HORIZONTAL Y 
                		TODO TIPO DE INFRAESTRUCTURA CON UN NIVEL DE CALIDAD SUPERIOR AL SOLICITADO POR 
                		NUESTROS CLIENTES.
              		</p>
            	</div>
          	</div>         
        </div>
	</div>
</div>
<div class="hr">	
	<span class="hr-inner"></span>
</div>    