<div class="breadcrumbs">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-sm-4">
				<h1>Partners</h1>
			</div>
			<div class="col-lg-8 col-sm-8">
				<ol class="breadcrumb pull-right">
					<li>
						<a href="/">Inicio</a>
					</li>
				</ol>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
    	<div class='col-md-offset-2 col-md-8 text-center'>
        	<h2>Empresas amigas de IEII</h2>
        </div>
 	</div>
   	<div class="row">
   		<div class="col-md-offset-2 col-md-8 mar-b-30">
        	<div class="carousel slide" data-ride="carousel" id="quote-carousel">
            <!-- Bottom Carousel Indicators 
            	<ol class="carousel-indicators">
              		<li data-target="#quote-carousel" data-slide-to="0" class="active"></li>              		
            	</ol>
            	<!-- Carousel Slides / Quotes 
            	Ponerle esta clase si quiero que haga lo de carousel-inner
            	-->
            	<div class="">
              		<!-- Quote 1 -->
              		<div class="item active">
                		<blockquote>
		          			<div class="row">
                    			<div class="col-sm-3 text-center">
                    				<a href="http://www.inncol.com" target="_new">
                      					<img class="img-circle" src="img/partners/inncolCirculo.png" style="width: 100px;height:100px;" alt="">
                    				</a>
                    			</div>
                    			<div class="col-sm-9">
                      				<p>
	                        		INNCOL Consulting es una empresa dedica al desarrollo de software generico y a la medida 
                      				</p>
                      				<a href="http://www.inncol.com" target="_new">
                      					<small>INNCOL Consulting - Software Developers</small>
                      				</a>
                    			</div>
                  			</div>
                		</blockquote>
              		</div>              		
              		<hr>
              		<!--  
              		<div class="item active">
                		<blockquote>
		          			<div class="row">
                    			<div class="col-sm-3 text-center">
                    				<a href="http://www.inncol.com" target="_new">
                      					<img class="img-circle" src="img/partners/inncolCirculo.png" style="width: 100px;height:100px;" alt="">
                    				</a>
                    			</div>
                    			<div class="col-sm-9">
                      				<p>
	                        		INNCOL Consulting es una empresa dedica al desarrollo de software generico y a la medida 
                      				</p>
                      				<a href="http://www.inncol.com" target="_new">
                      					<small>INNCOL Consulting - Software Developers</small>
                      				</a>
                    			</div>
                  			</div>
                		</blockquote>
              		</div> 
              		<!-- -->                        		
            	</div>
        	</div>
    	</div>
	</div>
</div>