<div class="gray-box">
    <div class="container">
        <div class="row">
            <div class="text-center feature-head">
                <h1>Ingenier&iacute;a</h1>                
            </div>
            <div class="services">
                <div class="col-lg-6 col-sm-6">
                    <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1.5s" data-wow-delay=".1s">
                        <i class="fa fa-cogs"></i>
                    </div>
                    <div class="content">
                        <h3 class="title">Ingenier&iacute;a de valor</h3>
                        <p>
                            Ingenir&iacute;a de valor
                        </p>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1.5s" data-wow-delay=".3s">
                        <i class="fa fa-bolt"></i>
                    </div>
                    <div class="content">
                        <h3 class="title">Instalaciones electricas</h3>
                        <p>
                            Instalaciones de Media y Baja tensi&oacute;n
                        </p>
                    </div>
                </div>
            </div>
            <div class="services">
                <div class="col-lg-12 col-sm-6">
                    <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1.5s" data-wow-delay=".5s">
                        <i class="fa fa-bolt"></i>
                    </div>
                    <div class="content">
                        <h3 class="title">Instalaciones Especiales</h3>                       
                        <ul>
							<li>SISTEMAS ITS</li>
                           	<li>Control de Acceso</li>
                            <li>Detecci&oacute;n y Extinci&oacute;n de incendios</li>
                            <li>Cable estructurado</li>
                            <li>Fibra optica</li>
                            <li>CCTV</li>
                            <li>Voz y Datos</li>                            	
                            <li>Hidraulica</li>
                            <li>HVAC</li>
                     	</ul>                                                   
                    </div>
                </div>                
            </div>           
        </div>
        <div class="row">
            <div class="text-center feature-head">
                <h1>Mantenimiento</h1>                
            </div>
            <div class="services">
            	<div class="col-lg-6 col-sm-6">
                    <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1.5s" data-wow-delay=".3s">
                        <i class="fa fa-bolt"></i>
                    </div>
                    <div class="content">
                        <h3 class="title">Instalaciones electricas</h3>
                        <ul>
                        	<li>Instalaciones electricas residenciales</li>
                        	<li>Subestaciones</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1.5s" data-wow-delay=".5s">
                        <i class="fa fa-bolt"></i>
                    </div>
                    <div class="content">
                        <h3 class="title">Instalaciones Especiales</h3>                       
                        <ul>
							<li>SISTEMAS ITS</li>
                           	<li>Control de Acceso</li>
                            <li>Detecci&oacute;n y Extinci&oacute;n de incendios</li>
                            <li>Cable estructurado</li>
                            <li>Fibra optica</li>
                            <li>CCTV</li>
                            <li>Voz y Datos</li>                            	
                            <li>Hidraulica</li>
                            <li>HVAC</li>
                     	</ul>                                                   
                    </div>
                </div>                       
            </div>                      
        </div>
        <div class="row">
            <div class="text-center feature-head">
                <h1>Instalaciones</h1>                
            </div>
            <div class="services">
            	<div class="col-lg-6 col-sm-6">
                    <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1.5s" data-wow-delay=".3s">
                        <i class="fa fa-bolt"></i>
                    </div>
                    <div class="content">
                        <h3 class="title">Instalaciones electricas</h3>
                        <ul>
                        	<li>Instalaciones electricas residenciales</li>
                        	<li>Subestaciones</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1.5s" data-wow-delay=".5s">
                        <i class="fa fa-bolt"></i>
                    </div>
                    <div class="content">
                        <h3 class="title">Instalaciones Especiales</h3>                       
                        <ul>
							<li>SISTEMAS ITS</li>
                           	<li>Control de Acceso</li>
                            <li>Detecci&oacute;n y Extinci&oacute;n de incendios</li>
                            <li>Cable estructurado</li>
                            <li>Fibra optica</li>
                            <li>CCTV</li>
                            <li>Voz y Datos</li>                            	
                            <li>Hidraulica</li>
                            <li>HVAC</li>
                     	</ul>                                                   
                    </div>
                </div>                       
            </div>                      
        </div>
    </div>
</div>