<?php 
error_reporting(E_ALL);
ini_set('display_errors', 1);			
?>	  		  		  		  		  		  		  	  		  			 
<html>
  	<head>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="description" content="Developed By M Abdur Rokib Promy">
	    <meta name="author" content="cosmic">
	    <meta name="keywords" content="Bootstrap 3, Template, Theme, Responsive, Corporate, Business">
	    <link rel="shortcut icon" href="/img/favicon.png">
	    <title>
	      IEII | <?php echo ucwords(strtolower($this->moduleName)); ?>
	    </title>
	    <!-- Bootstrap core CSS -->
	    <link href="/styles/bootstrap.min.css" rel="stylesheet">
	    <link href="/styles/theme.css" rel="stylesheet">
	    <link href="/styles/bootstrap-reset.css" rel="stylesheet">
	    <!-- <link href="styles/bootstrap.min.css" rel="stylesheet">-->
	    <!--external styles-->
	    <link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
	    <link rel="stylesheet" href="/styles/flexslider.css"/>
	    <link href="/assets/bxslider/jquery.bxslider.css" rel="stylesheet" />
	    <link rel="stylesheet" href="/styles/animate.css">
	    <link rel="stylesheet" href="/assets/owlcarousel/owl.carousel.css">
	    <link rel="stylesheet" href="/assets/owlcarousel/owl.theme.css">
	
	    <link href="/styles/superfish.css" rel="stylesheet" media="screen">
	    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
	    <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> -->
	    <!-- Custom styles for this template -->
	    <link rel="stylesheet" type="text/css" href="/styles/component.css">
	    <link href="/styles/style.css" rel="stylesheet">
	    <link href="/styles/style-responsive.css" rel="stylesheet" />
	
	    <link rel="stylesheet" type="text/css" href="/styles/parallax-slider/parallax-slider.css" />
	    <script type="text/javascript" src="/scripts/parallax-slider/modernizr.custom.28468.js">
	    </script>
	    <?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript() ?> 
  	</head>
  	<body>
  		<?php echo $this->render("_partials/menu.phtml"); ?>
  		<?php echo $this->layout()->content; ?>
  		<?php echo $this->render("_partials/footer.phtml"); ?>	  		    
  	</body>
</html>			