<?php 
error_reporting(E_ALL);
ini_set('display_errors', 1);			
?>	  		  		  		  		  		  		  	  		  			 
<html>
  	<head>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="description" content="IEII CONSULTORIA">
	    <meta name="author" content="cosmic">
	    <meta name="keywords" content="IEII, inncol, INNCOL, ingenieria, ingenirer&iacute;a, ingeniería, instalaciones, electricas">	    
	    <title>
	      IEII | <?php echo ucwords(strtolower($this->moduleName)); ?>
	    </title>
	    <!-- Bootstrap core CSS -->
	    <link type="text/css" rel="stylesheet" href="/styles/bootstrap.min.css" >
	    <link type="text/css" rel="stylesheet" href="/styles/theme.css"/>
	    <link type="text/css" rel="stylesheet" href="/styles/bootstrap-reset.css"/>
	    <link type="text/css" rel="stylesheet" href="/assets/font-awesome/css/font-awesome.css"/>
	    <link type="text/css" rel="stylesheet" href="/styles/flexslider.css"/>
	    <link type="text/css" rel="stylesheet" href="/assets/bxslider/jquery.bxslider.css"/>
	    <link type="text/css" rel="stylesheet" href="/styles/animate.css"/>
	    <link type="text/css" rel="stylesheet" href="/assets/owlcarousel/owl.carousel.css"/>
	    <link type="text/css" rel="stylesheet" href="/assets/owlcarousel/owl.theme.css"/>	
	    <link type="text/css" rel="stylesheet" href="/styles/superfish.css" media="screen"/>
	    <link type="text/css" rel="stylesheet" href='http://fonts.googleapis.com/css?family=Lato'/>	    	    
	    <link type="text/css" rel="stylesheet" href="/styles/component.css">
	    <link type="text/css" rel="stylesheet" href="/styles/style.css"/>
	    <link type="text/css" rel="stylesheet" href="/styles/style-responsive.css"/>
	    <link type="text/css" rel="stylesheet" href="/styles/parallax-slider/parallax-slider.css" />

	    <script type="text/javascript" src="/scripts/parallax-slider/modernizr.custom.28468.js"></script>
	    <script type="text/javascript" src="/scripts/jquery-1.11.3.js"></script>	    
	    <?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript() ?> 
  	</head>
  	<body>
  		<?php echo $this->render("_partials/menu.phtml"); ?>
  		<?php echo $this->layout()->content; ?>
  		<?php echo $this->render("_partials/footer.phtml"); ?>	  		    
  	</body>
</html>			