<footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-sm-3 address wow fadeInUp" data-wow-duration="2s" data-wow-delay=".1s">
            <h1>
              Informaci&oacute;n de contacto
            </h1>
            <address>
              <p><i class="fa fa-home pr-10"></i>Direcci&oacute;n: </p>
              <p><i class="fa fa-globe pr-10"></i>Ciudad de M&eacute;xico </p>              
              <p><i class="fa fa-phone pr-10"></i>Tel&eacute;fono : +52 1 55 1149 6118 </p>
              <p><i class="fa fa-envelope pr-10"></i>Email : <a href="mailto:contacto@ieii.com.mx">contacto@ieii.com.mx</a></p>
            </address>
          </div>
  		<div class="col-lg-3 col-sm-3 wow fadeInUp animated" data-wow-delay=".3s" data-wow-duration="2s" style="visibility: visible; animation-duration: 2s; animation-delay: 0.3s; animation-name: fadeInUp;" data-wow-animation-name="fadeInUp">	
            <h1>Ponte al d&iacute;a</h1>
        	<div class="tweet-box">
				<i class="fa fa-twitter"></i>
				<em>
					Para futuros proyectos sigue a
					<a href="http://www.inncol.com" target="_new">INNCOL</a>						
					<a href="http://www.twitter.com/INNCOLSD">twitter.com/INNCOL</a>
				</em>
			</div>             
        </div>
          <div class="col-lg-3 col-sm-3">
            <div class="page-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".5s">
              <h1>
                Nuestro Men&uacute;
              </h1>
              <ul class="page-footer-list">
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="/">INICIO</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="/acercade">ACERCA DE</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="/servicios">SERVICIOS</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="/partners">PARTNERS</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="/contactanos">CONTACTANOS</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-sm-3">
            <div class="text-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".7s">
              <h1>
                IEII
              </h1>
              <p style="text-align:justify;">
              		EMPRESA DE INGENIER&Iacute;A Y CONSTRUCCI&Oacute;N DE INSTALACIONES 
					ELECTROMEC&Aacute;NICAS, BUSCAMOS OFRECER A NUESTROS CLIENTES SOLUCIONES INNOVADORAS Y 
					DE ALTA CALIDAD T&Eacute;CNICA
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- footer end -->
    <!--small footer start -->
	    <footer class="footer-small">
	        <div class="container">
	            <div class="row">
	                <div class="col-lg-6 col-sm-6 pull-right">
	                    <ul class="social-link-footer list-unstyled">
	                        <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".1s"><a href="#"><i class="fa fa-facebook"></i></a></li>
	                        <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".2s"><a href="#"><i class="fa fa-google-plus"></i></a></li>
	                        <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".4s"><a href="#"><i class="fa fa-linkedin"></i></a></li>
	                        <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".5s"><a href="#"><i class="fa fa-twitter"></i></a></li>	                        
	                    </ul>
	                </div>
	                <div class="col-md-4">
	                  <div class="copyright">
	                    <p>&copy; IEII 2016 - Powered by <a id="inncol" href="http://www.inncol.com" target="_new">INNCOL</a>&reg;.</p>
	                  </div>
	                </div>
	            </div>
	        </div>
	    </footer>
	    <!--small footer end-->
	    <script src="/scripts/jquery-1.8.3.min.js"></script>
	    <script src="/scripts/bootstrap.min.js"></script>
	    <script type="text/javascript" src="/scripts/hover-dropdown.js"></script>
	    <script defer src="/scripts/jquery.flexslider.js"></script>
	    <script type="text/javascript" src="/assets/bxslider/jquery.bxslider.js"></script>
	    <script type="text/javascript" src="/scripts/jquery.parallax-1.1.3.js"></script>
	    <script src="/scripts/wow.min.js"></script>
	    <script src="/assets/owlcarousel/owl.carousel.js"></script>
	    <script src="/scripts/jquery.easing.min.js"></script>
	    <script src="/scripts/link-hover.js"></script>
	    <script src="/scripts/superfish.js"></script>
	    <script type="text/javascript" src="/scripts/parallax-slider/jquery.cslider.js"></script>
    	<script type="text/javascript">
	      $(function() {
	
	        $('#da-slider').cslider({
	          autoplay    : true,
	          bgincrement : 100
	        });
	
	      });
    	</script>
    	<!--common script for all pages-->
    	<script src="/scripts/common-scripts.js"></script>	
	    <script type="text/javascript">
	      jQuery(document).ready(function() {
	        $('.bxslider1').bxSlider({
	          minSlides: 5,
	          maxSlides: 6,
	          slideWidth: 360,
	          slideMargin: 2,
	          moveSlides: 1,
	          responsive: true,
	          nextSelector: '#slider-next',
	          prevSelector: '#slider-prev',
	          nextText: 'Onward →',
	          prevText: '← Go back' 
	        });
	      });
	    </script>
	    <script>
	      	$('a.info').tooltip();
	     	$(window).load(function() {
	        	$('.flexslider').flexslider({
	          		animation: "slide",
	          		start: function(slider) {
	            		$('body').removeClass('loading');
	          		}
	        	});
	      	});
	      	$(document).ready(function() {
		        $("#owl-demo").owlCarousel({
	          		items : 4
	        	});
	      	});
	      	jQuery(document).ready(function(){
		        jQuery('ul.superfish').superfish();
	      	});
	      	new WOW().init();
	    </script>