<header class="head-section">
	<div class="navbar navbar-default navbar-static-top container">
    	<div class="navbar-header">
        	<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
         	</button>
           	<a class="navbar-brand" href="index.html">              
            	<img src="/img/ieii.png" width="200px" /> 
            </a>
    	</div>
		<div class="navbar-collapse collapse">
        	<ul class="nav navbar-nav">
            	<li>
                	<a href="/">Inicio</a>                      
               	</li>
               	<li class="dropdown">
                      <a class="dropdown-toggle" data-close-others="false" data-delay="0" data-hover=
                      "dropdown" data-toggle="dropdown" href="/servicios">Servicios <i class="fa fa-angle-down"></i>
                      </a>
                      <ul class="dropdown-menu">
                          <li >
                              <a href="/ingenieria" tabindex="0">Ingenier&iacute;a</a>                              
                          </li>
                          <li>
                              <a href="/mantenimiento" tabindex="-1">Mantenimiento</a>                              
                          </li>
                          <li >
                              <a href="/instalaciones" tabindex="-1">Instalaciones</a>                             
                          </li>
                      </ul>
                  </li>
              	<li>
                  	<a href="/acercade">Acerca de</a>                      
               	</li>              
                <li>
                  	<a href="/partners">Partners</a>                      
                </li>                                
                <li>
                	<a href="/contactanos">Contactanos</a>
                </li>
               	<li>
               		<input class="form-control search" placeholder=" Search" type="text">
               	</li>                                          
              </ul>
          </div>
      </div>
 </header>