 <div class="white-bg">    
    <div class="container career-inner">
        <div class="row">
            <div class="col-md-12 career-head">
                <h1 class="wow fadeIn">
                	<br/>
                	Acercar de IEII
                	</br>
                </h1>
            </div>
        </div>
 	</div>
</div>
<div class="white-bg">      
	<div class="container career-inner">		
        <hr>
        <div class="row">
            <div class="col-md-12 wow fadeIn">
                <p style="text-align:justify;">
                	Instalaciones Electromecanicas, Ingenier&iacute;a e Innovaci&oacute;n es una empresa mexicana que se ha fundado con el objetivo de convertirse 
                	en una de las principales empresas de servicios, a fin de dar soluciones y cubrir necesidades a nuestros clientes, ademas de anticipar ideas e
                	innovaciones que en un mediano o largo plazo pueden marcar la diferencia en cuanto a productividad se refiere
                	<br/>
                </p>                
            </div>
            <div class="col-md-4 col-md-offset-4 career-contact">
                <p class="text-center wow pulse">
                	<i class="fa fa-envelope pr-10"></i>
                	<b>Correo  de contacto: </b>
                	<em>contacto@ieii.com.mx</em>
                </p>
            </div>
        </div>
        <hr>
		<div class="row">
			<div class="col-md-6">
		    	<div class="candidate wow fadeInLeft">
					<h1>Misi&oacute;n</h1>
					<p style="text-align: justify;">
					Ser una empresea referente a nivel nacional en la creaci&oacute;n  e implementacion de soluciones innovadoras y de alta calidad T&eacute;cnicas con un alto nivel de calidad.
					</p>					
				</div>		
				<hr>
			</div>
		 	<div class="col-md-6">
				<div class="candidate wow fadeInRight">
					<h1>Visi&oacute;n</h1>
					<p style="text-align: justify;">
					Como empresa de Ingenier&iacute;a y contrucci&oacute;n de instalacione electromec&aacute;nicas, buscamos ofrecer a 
					nuestros clientes soluciones innovadoras y de alta calidad t&eacute;cnica, mediante la constante capacitaci&oacute;n
					de nuestro equipo de profesionales en los distintos campos de la ingenier&iacute;a en los que nos desempe&ntilde;amos
					ya que estamos seguros de que las soluciones m&aacute;s adecuadas se elaboran a trav&eacute;s del conocimiento.	
					</p>					
				</div>
				<hr>		
			</div>
		</div>
	</div>
</div>